### ISSUE TITLE
关于训练与重建时的DnCNN通道数问题

### ISSUE THREAD

**Issue by CharlesIsMeee** [Houruizhi/IDPCNN#1]
请问一下，这个代码中，在训练 DnCNN时，参数设置的模型输入通道与输出通道为双通道，可为何transform中， 返回的数据集为单通道数据集， 而在重建时的transform中又是返回的双通道的数据集， 这里我有点没太懂。我第一次是将yaml文件中的通道数改为1，训练了DnCNN, 然后重建时，需要双通道的模型参数。 所以我是不是应该将训练DnCNN时的transform中返回的数据集改成双通道来训练. 谢谢~

**Comment by Houruizhi** [comment]
您好，您的邮件我已经收到。

**Comment by Houruizhi** [comment]
我这里默认是MRI重建，所以重建的数据是复数，转换成torch.tensor之后是双通道，两个通道分别代表实数和复数。所以训练的时候，数据应当是复数数据，转换成tensor之后是双通道。
如果你是做自然图像的compressed sensing，那就训练的时候用单通道。训练完成后，重建的时候，请把重建的transform类加载图像那一步也改成单通道。

**Comment by Houruizhi** [comment]
这是我的初始工作，代码写的很糙，我自己的代码也在迭代当中，新的代码会随着新论文的发表也公布出来。但这个代码应该是不会再改动了，如果有问题可以随时问我。

**Comment by CharlesIsMeee** [comment]
非常感谢您，我大概知道原因了，我也是做的MRI的重建，但是我使用该源码训练DnCNN时，发现其yaml中配置的DnCNN通道为双通道，但是我用我的数据集返回的数据为单通道数据，因为代码中的numpy2tensor，会将复数转为双通道，而我用的MRI数据是已经为实数的MRI图像，所以numpy2tensor不会将其转换为双通道数据。而您使用的训练数据集应该是复数MRI图像，所以可以训练的是双通道的模型，而重建的transform类由于傅里叶变换会将实数图像也转为复数类型来处理，所以重建时数据又变为双通道了，导致我训练时与重建时的通道不一致。所以我只要将我的数据集改为复数类型，就可以在训练与重建时保持相同的通道数了，如果我的理解是对的话您就可以关闭这个issue了，再次感谢！！！

**Comment by Houruizhi** [comment]
祝顺利！！！

**Comment by CharlesIsMeee** [comment]
> 这是我的初始工作，代码写的很糙，我自己的代码也在迭代当中，新的代码会随着新论文的发表也公布出来。但这个代码应该是不会再改动了，如果有问题可以随时问我。

代码不糙，结构很清晰，也很容易阅读

**Comment by Houruizhi** [comment]
> > 这是我的初始工作，代码写的很糙，我自己的代码也在迭代当中，新的代码会随着新论文的发表也公布出来。但这个代码应该是不会再改动了，如果有问题可以随时问我。
> 
> 代码不糙，结构很清晰，也很容易阅读

好的，欢迎使用这个代码和引用我的小小工作~

**Comment by Houruizhi** [comment]
您好，您的邮件我已经收到。
