### ISSUE TITLE
关于环境问题

### ISSUE THREAD

**Issue by wwHwo** [Houruizhi/IDPCNN#2]
你好，我在readme里面没有看到torch版本和其他包的版本，请问您是在什么环境下做的训练和测试呢，torch版本对做实验时的结果会有影响吗

**Comment by Houruizhi** [comment]
您好，您的邮件我已经收到。

**Comment by Houruizhi** [comment]
您好，这个项目里没用到复杂的包，而且算法比较简单，所以只要是训练和测试过程中不报错，就是可以出效果的。你先试试，如果有问题随时问我。

**Comment by wwHwo** [comment]
好的，谢谢

**Comment by Houruizhi** [comment]
还是推荐你看我的另一个PnP方法的代码，[click here](https://github.com/Houruizhi/TRPA)，效果可达到state-of-the-art
